#!/bin/bash

echo "🎵 Instructions pour tester la détection AudioQR"
echo "=============================================="
echo ""
echo "1. 📱 Lancez l'app et cliquez sur 'DÉTECTER LE SON'"
echo ""
echo "2. 🔊 Pendant la détection (30 secondes) :"
echo "   - Montez le VOLUME au MAXIMUM"
echo "   - Placez le téléphone PRÈS du haut-parleur (5-10cm)"
echo "   - Assurez-vous qu'il n'y a pas de bruit ambiant"
echo ""
echo "3. 🎧 Types de signaux à tester :"
echo "   - Signal AudioQR de l'app Minfo officielle"
echo "   - Fichier audio .wav/.mp3 contenant un signal"
echo "   - Signal généré par un autre device"
echo ""
echo "4. 📊 Surveillez les logs :"
echo "   - '🔍 Moteur actif - En écoute...' toutes les 5s"
echo "   - '🎯 SIGNAL DÉTECTÉ !' si ça marche"
echo "   - '⏰ Timeout' après 30s si rien"
echo ""
echo "5. 🔧 Si ça ne marche toujours pas :"
echo "   - Vérifiez que le signal est bien un AudioQR Cifrasoft"
echo "   - Testez avec différents volumes/distances"
echo "   - Essayez dans un environnement plus silencieux"
echo ""
echo "✅ Le SDK fonctionne - c'est maintenant un problème de signal/environnement"
