# Spécifiez explicitement le projet et le workspace
def setup_permissions(permissions)
  Array(permissions).each do |permission|
    case permission
    when 'microphone'
      ENV['PERMISSION_MICROPHONE'] = '1'
    end
  end
end
project 'Runner.xcodeproj'
workspace 'Runner.xcworkspace'

platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  setup_permissions([
    'microphone'
  ])

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # 1. Force iOS 12.0 pour tout le monde
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'

      # 2. ACTIVE LA PERMISSION MICROPHONE (Crucial pour iOS)
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_MICROPHONE=1'
      ]
    end

    # Configuration spécifique Cifrasoft
    if target.name == 'Runner'
      target.build_configurations.each do |config|
        config.build_settings['OTHER_LDFLAGS'] ||= []
        config.build_settings['OTHER_LDFLAGS'] << '-force_load'
        config.build_settings['OTHER_LDFLAGS'] << '$(SRCROOT)/SCSTB_LibraryU.a'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= []
        config.build_settings['HEADER_SEARCH_PATHS'] << '$(SRCROOT)'
      end
    end
  end
end